name: Remove Label
on:
  pull_request:
    types: [synchronize]
  issue_comment:
    types: [created]
jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: bug
