name: Windows CI
on:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install opam
        run: |
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/kit-ty-kate/opam/c614e391f132533c1f051fe65d63ac3793c9ea26/shell/install.ps1 -OutFile install.ps1
        .\install.ps1
#          "C:\Program Files\opam\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Init opam
        run: opam init -yn ./opam-repository

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        #with:
        #  since_last_remote_commit: true

      - name: List all changed packages
        id: changed-packages
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          output = @()
          Foreach ($file in $env:ALL_CHANGED_FILES) {
            switch -Regex ($file) {
              '^packages/[^/]*/([^/]*)/.*' { ouptput += "$($matches[1])"; Break }
              default { echo "$file skipped"; Break }
            }
          done
          $outputJson = $output | ConvertTo-Json
          echo "::set-output name=data::$outputJson"

      - name: Install packages
        env:
          ALL_CHANGED_PACKAGES: ${{ steps.changed-packages.outputs.data }}
        run: |
          pkgs = ${ALL_CHANGED_PACKAGES} | ConvertFrom-Json
          Foreach ($pkg in $pkgs) {
            opam install --confirm-level=unsafe-yes "$pkg"
          }
